package specqr

import (
	"bytes"
	"crypto/sha256"
	"fmt"
	"reflect"
	"strings"
	"testing"
)

func TestCorePadding(t *testing.T) {
	tests := []struct {
		bits []byte
		want []byte
	}{
		{nil, []byte{0, 0xec, 0x11, 0xec, 0x11, 0xec, 0x11, 0xec, 0x11}},
		{[]byte{1, 0, 1}, []byte{0xa0, 0xec, 0x11, 0xec, 0x11, 0xec, 0x11, 0xec, 0x11}},
		{bytes.Repeat([]byte{1}, 72), bytes.Repeat([]byte{255}, 9)},
		{bytes.Repeat([]byte{1}, 71), append(bytes.Repeat([]byte{255}, 8), 254)},
		{bytes.Repeat([]byte{1}, 68), append(bytes.Repeat([]byte{255}, 8), 240)},
		{bytes.Repeat([]byte{1}, 64), append(bytes.Repeat([]byte{255}, 8), 0)},
	}
	for _, tc := range tests {
		got, e := PadDataBits(tc.bits, 1, H)
		if e != nil || !bytes.Equal(got, tc.want) {
			t.Fatalf("padding %d: %x %v", len(tc.bits), got, e)
		}
	}
	if _, e := PadDataBits(make([]byte, 73), 1, H); e == nil {
		t.Fatal("oversize accepted")
	}
	if _, e := PadDataBits([]byte{2}, 1, H); e == nil {
		t.Fatal("non-bit accepted")
	}
}
func TestGFExhaustive(t *testing.T) {
	for left := 0; left < 256; left++ {
		for right := 0; right < 256; right++ {
			product := 0
			for bit := 0; bit < 8; bit++ {
				if right&(1<<bit) != 0 {
					product ^= left << bit
				}
			}
			for bit := 14; bit >= 8; bit-- {
				if product&(1<<bit) != 0 {
					product ^= 0x11d << (bit - 8)
				}
			}
			got, e := GFMultiply(left, right)
			if e != nil || got != product {
				t.Fatalf("%d*%d=%d want %d", left, right, got, product)
			}
		}
	}
}
func TestReedSolomon(t *testing.T) {
	div, e := ReedSolomonDivisor(7)
	if e != nil || !bytes.Equal(div, []byte{1, 127, 122, 154, 164, 11, 68, 117}) {
		t.Fatal(div, e)
	}
	for _, degree := range []int{1, 7, 10, 18, 30, 255} {
		data := make([]byte, 40)
		for i := range data {
			data[i] = byte(i)
		}
		parity, e := ReedSolomonRemainder(data, degree)
		if e != nil || len(parity) != degree {
			t.Fatal(degree, e)
		}
		rem, e := ReedSolomonRemainder(append(data, parity...), degree)
		if e != nil || !bytes.Equal(rem, make([]byte, degree)) {
			t.Fatal(degree, rem, e)
		}
	}
}

// This digest was independently generated by the pinned, user-owned JavaScript
// SpecQR source, not by the Go port. It covers all 40 versions, four ECC levels,
// eight forced masks, exact interleaved codewords, exact matrices and penalties.
func TestAllCoreMatricesPinnedJavaScript(t *testing.T) {
	hash := sha256.New()
	for version := 1; version <= 40; version++ {
		for _, ecc := range []ECC{L, M, Q, H} {
			info, e := BlockInfo(version, ecc)
			if e != nil {
				t.Fatal(e)
			}
			data := make([]byte, info.DataCodewords)
			for i := range data {
				data[i] = byte((i*37 + version*11 + int(ecc[0])) % 256)
			}
			coded, e := InterleaveCodewords(data, version, ecc)
			if e != nil {
				t.Fatal(e)
			}
			if len(coded.Codewords) != info.RawCodewords || len(coded.Blocks) != info.Blocks || coded.ErrorCorrectionCodewords != info.Blocks*info.ECCPerBlock {
				t.Fatal("block metadata", version, ecc)
			}
			var joined []byte
			prev := -1
			for _, block := range coded.Blocks {
				joined = append(joined, block.Data...)
				if prev >= 0 && (len(block.Data) < prev || len(block.Data) > prev+1) {
					t.Fatal("unordered blocks")
				}
				prev = len(block.Data)
				input := append(append([]byte(nil), block.Data...), block.ECC...)
				remainder, e := ReedSolomonRemainder(input, info.ECCPerBlock)
				if e != nil || !bytes.Equal(remainder, make([]byte, info.ECCPerBlock)) {
					t.Fatal("invalid parity", version, ecc, e)
				}
			}
			if !bytes.Equal(joined, data) {
				t.Fatal("data loss")
			}
			hash.Write(coded.Codewords)
			for mask := 0; mask < 8; mask++ {
				built, e := BuildMatrix(coded.Codewords, version, ecc, &mask)
				if e != nil {
					t.Fatal(version, ecc, mask, e)
				}
				if len(built.Matrix) != 4*version+17 || !built.Matrix[len(built.Matrix)-8][8] {
					t.Fatal("matrix invariants")
				}
				fmt.Fprintf(hash, "%d,%s,%d,%d\n", version, ecc, mask, built.Penalty)
				for _, row := range built.Matrix {
					for _, v := range row {
						if v {
							hash.Write([]byte{'1'})
						} else {
							hash.Write([]byte{'0'})
						}
					}
					hash.Write([]byte{'\n'})
				}
			}
		}
	}
	if got := fmt.Sprintf("%x", hash.Sum(nil)); got != "fd95d49c51a18746b2de4f37a034c1c607424e7361e00b846996b9ede597f772" {
		t.Fatalf("all-matrix pinned SpecQR digest: %s", got)
	}
}
func TestAutomaticMasks(t *testing.T) {
	for _, v := range []int{1, 7, 32, 40} {
		raw, _ := RawCodewordCount(v)
		data := make([]byte, raw)
		for i := range data {
			data[i] = byte(i*71 + v)
		}
		built, e := BuildMatrix(data, v, Q, nil)
		if e != nil || len(built.MaskPenalties) != 8 {
			t.Fatal(e)
		}
		best := built.MaskPenalties[0]
		for _, p := range built.MaskPenalties {
			if p.Penalty < best.Penalty {
				best = p
			}
			forced, e := BuildMatrix(data, v, Q, &p.MaskPattern)
			if e != nil || forced.Penalty != p.Penalty {
				t.Fatal(e)
			}
		}
		if best.MaskPattern != built.MaskPattern || best.Penalty != built.Penalty {
			t.Fatal("wrong mask")
		}
		fixed, e := BuildMatrix(data, v, Q, &built.MaskPattern)
		if e != nil || !reflect.DeepEqual(fixed.Matrix, built.Matrix) {
			t.Fatal("auto differs from fixed")
		}
	}
}
func TestPenaltyRules(t *testing.T) {
	tests := []struct {
		rows []string
		want int
	}{{[]string{"11111", "01010", "10101", "01010", "10101"}, 23}, {[]string{"11010", "11010", "00101", "01010", "10101"}, 3}, {strings.Split(strings.Repeat("1111111111,", 9)+"1111111111", ","), 503}}
	rows := []string{"10111010000"}
	for i := 1; i < 11; i++ {
		if i%2 == 1 {
			rows = append(rows, "01010101010")
		} else {
			rows = append(rows, "10101010101")
		}
	}
	tests = append(tests, struct {
		rows []string
		want int
	}{rows, 40})
	for _, tc := range tests {
		grid := make([][]bool, len(tc.rows))
		for y, row := range tc.rows {
			grid[y] = make([]bool, len(row))
			for x := range row {
				grid[y][x] = row[x] == '1'
			}
		}
		got, e := PenaltyScore(grid)
		if e != nil || got != tc.want {
			t.Fatal(got, tc.want, e)
		}
		transpose := make([][]bool, len(grid))
		for y := range grid {
			transpose[y] = make([]bool, len(grid))
			for x := range grid {
				transpose[y][x] = grid[x][y]
			}
		}
		got, e = PenaltyScore(transpose)
		if e != nil || got != tc.want {
			t.Fatal("transpose", got, e)
		}
	}
}
func TestCoreRejectsInvalidInputs(t *testing.T) {
	for _, v := range []int{-1, 0, 41, int(^uint(0) >> 1)} {
		if _, e := BuildMatrix(nil, v, L, nil); e == nil {
			t.Fatal(v)
		}
	}
	for _, v := range []int{-1, 256} {
		if _, e := GFMultiply(v, 1); e == nil {
			t.Fatal(v)
		}
		if _, e := GFMultiply(1, v); e == nil {
			t.Fatal(v)
		}
	}
	for _, d := range []int{-1, 0, 256} {
		if _, e := ReedSolomonDivisor(d); e == nil {
			t.Fatal(d)
		}
	}
	if _, e := ReedSolomonRemainder(make([]byte, 3707), 7); e == nil {
		t.Fatal("oversize RS")
	}
	if _, e := InterleaveCodewords(nil, 1, L); e == nil {
		t.Fatal("short data")
	}
	for _, m := range []int{-1, 8} {
		if _, e := BuildMatrix(make([]byte, 26), 1, L, &m); e == nil {
			t.Fatal(m)
		}
	}
	if _, e := BuildMatrix(make([]byte, 25), 1, L, nil); e == nil {
		t.Fatal("short codewords")
	}
	if _, e := PenaltyScore([][]bool{{true, false}}); e == nil {
		t.Fatal("nonsquare")
	}
	if _, e := PenaltyScore(nil); e == nil {
		t.Fatal("empty")
	}
	for _, xy := range []int{-1, 177} {
		if _, e := MaskCondition(0, xy, 0); e == nil {
			t.Fatal(xy)
		}
	}
}
func FuzzCorePublicInputs(f *testing.F) {
	f.Add([]byte{1, 0, 1}, 1, "L", 0)
	f.Add([]byte{}, 0, "?", 9)
	f.Fuzz(func(t *testing.T, data []byte, version int, level string, mask int) {
		_, _ = PadDataBits(data, version, ECC(level))
		_, _ = InterleaveCodewords(data, version, ECC(level))
		_, _ = BuildMatrix(data, version, ECC(level), &mask)
		_, _ = ReedSolomonRemainder(data, mask)
		_, _ = GFMultiply(version, mask)
		_, _ = MaskCondition(mask, version, len(data))
	})
}
