#!/usr/bin/env python3
"""Generate frozen Unicode 15.0.0 data for SpecQR-Go's conservative host profile.

The runtime is stdlib-only and performs no Unicode normalization. This profile
is not full IDNA or UTS #46: combining marks, compatibility-unstable characters,
unassigned code points, and contextual Hangul Jamo are deliberately rejected.
Generate or check with Python using unicodedata.unidata_version == 15.0.0.
Unicode data license: https://www.unicode.org/license.txt (LICENSE-UNICODE).
"""
from pathlib import Path
import hashlib
import json
import sys
import unicodedata as ud

VERSION = "15.0.0"
DESTINATION = Path(__file__).resolve().parents[1] / "idna_table.go"
if ud.unidata_version != VERSION:
    raise SystemExit(f"Expected Unicode {VERSION}; found {ud.unidata_version}")


def ranges(values):
    result = []
    for value in values:
        if result and value == result[-1][1] + 1:
            result[-1][1] = value
        else:
            result.append([value, value])
    return result


rejected, lowercase, rtl_letters, arabic_digits = [], [], [], []
for code in range(0x110000):
    scalar = chr(code)
    category = ud.category(scalar)
    if code >= 128 and (
        category[0] in "MCZ"
        or ud.normalize("NFKC", scalar) != scalar
        or (scalar.casefold() != scalar.lower() and scalar not in "ßς")
        or 0x2FF0 <= code <= 0x2FFF
        or code in (0xFFFC, 0xFFFD)
        or 0x1100 <= code <= 0x11FF
        or 0xA960 <= code <= 0xA97F
        or 0xD7B0 <= code <= 0xD7FF
    ):
        rejected.append(code)
    lower = scalar.lower()
    if lower != scalar:
        lowercase.append([code, [ord(c) for c in lower]])
    if ud.bidirectional(scalar) in ("R", "AL"):
        rtl_letters.append(code)
    if ud.bidirectional(scalar) == "AN":
        arabic_digits.append(code)

records = {
    "unicode": VERSION,
    "rejected": ranges(rejected),
    "lowercase": lowercase,
    "rtlLetters": ranges(rtl_letters),
    "arabicDigits": ranges(arabic_digits),
}
checksum = hashlib.sha256(json.dumps(records, ensure_ascii=True, separators=(",", ":")).encode()).hexdigest()
output = [
    "// Code generated by tools/generate_idna_profile.py; DO NOT EDIT.",
    "// Conservative hostname data; not complete IDNA or UTS #46.",
    f"// Unicode data version: {VERSION}; derived via Python stdlib unicodedata.",
    "// Unicode data license: https://www.unicode.org/license.txt (LICENSE-UNICODE).",
    f"// Semantic-record SHA-256: {checksum}",
    "// Reject marks, controls/format/unassigned, separators, NFKC-unstable scalars,",
    "// non-deviation casefold changes, ideographic description operators,",
    "// object/replacement symbols, and contextually composing Hangul Jamo.",
    "",
    "package specqr",
    "",
    "type gs1IDNARange struct{ first, last rune }",
    "type gs1IDNALower struct {",
    "\tscalar rune",
    "\tvalue  string",
    "}",
    "",
]
for name, key in [("gs1IDNARejected", "rejected"), ("gs1IDNARTLLetters", "rtlLetters"), ("gs1IDNAArabicDigits", "arabicDigits")]:
    output.append(f"var {name} = [...]gs1IDNARange{{")
    for start, end in records[key]:
        output.append(f"\t{{0x{start:X}, 0x{end:X}}},")
    output.extend(["}", ""])
output.append("var gs1IDNALowercase = [...]gs1IDNALower{")
for code, points in lowercase:
    encoded = "".join(f"\\u{point:04X}" if point <= 0xFFFF else f"\\U{point:08X}" for point in points)
    output.append(f'\t{{0x{code:X}, "{encoded}"}},')
output.extend(["}", ""])
content = "\n".join(output)
if len(sys.argv) > 1 and sys.argv[1] == "--check":
    if DESTINATION.read_text(encoding="utf-8") != content:
        raise SystemExit("idna_table.go differs; regenerate using the pinned Unicode database")
    print("Unicode profile tables match the pinned generator")
else:
    DESTINATION.write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {DESTINATION.name}: {len(records['rejected'])} rejection ranges, {len(lowercase)} mappings; {checksum}")
